CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    conversation_id BIGINT UNSIGNED NOT NULL,
    conversation_type TINYINT NOT NULL,
    owner_user_id BIGINT UNSIGNED NOT NULL,
    peer_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    group_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_message_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_message_preview VARCHAR(255) NOT NULL DEFAULT '',
    last_message_at BIGINT NOT NULL DEFAULT 0,
    unread_count INT NOT NULL DEFAULT 0,
    pinned TINYINT NOT NULL DEFAULT 0,
    muted TINYINT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY uk_owner_conversation (owner_user_id, conversation_id),
    INDEX idx_owner_updated (owner_user_id, updated_at),
    INDEX idx_owner_unread (owner_user_id, unread_count),
    INDEX idx_conversation_id (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
