{
 "title": "NebulaIM",
 "tags": [ "nebulaim" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nebula_gateway_active_connections"
    }
   ]
  },
  {
   "title": "Gateway Packets per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(nebula_gateway_packets_total[1m])"
    }
   ]
  },
  {
   "title": "Successful Direct Messages per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nebula_message_send_single_success_total[1m])"
    }
   ]
  },
  {
   "title": "Push Handling Failures per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nebula_push_kafka_handle_failed_total[1m])"
    }
   ]
  }
 ]
}